apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-rtf-ingress
  namespace: rtf 
  labels:
spec:
  ingressClassName: rtf-nginx 
  tls: 
  - hosts:
      - app-name.example.com
    secretName: example-tls
  rules:
  - host: app-name.example.com 
    http:
      paths: 
      - pathType: Prefix
        path: / 
        backend: 
          service:
            name: service-name
            port:
              name: service-port
