apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-gke-rtf-ingress-template
  namespace: 4956d3d6-14d3-423b-9165-4a39038ad29
spec:
  ingressClassName: rtf-nginx
  rules:
  - host: rtf-on-gke.mulesoftdemo.com
    http:
      paths:
      - path: /app-name
        pathType: Prefix
        backend:
          service:
            name: service-name
            port:
              name: service-port
