apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-rtf-ingress
  namespace: rtf 
  labels:
spec:
  ingressClassName: rtf-nginx
  rules:
  - host: rtf-on-gke.mulesoftdemo.com
    http:
      paths: 
      - pathType: Prefix
        path: /app-name 
        backend: 
          service:
            name: service-name
            port:
              name: service-port
